apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app1
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/tanzu
      ref:
        branch: master
